### PR TITLE
oasis-test-runner: Log watcher fixes and improvements

### LINKED ISSUE #2355: oasis-test-runner: Ensure each node gets its own set of log watcher handlers
Currently, all created log watchers get the same copy of the configured log watcher handlers:
https://github.com/oasislabs/oasis-core/blob/f30484fa34ce0b7d333579540be1277be4fdae83/go/oasis-test-runner/oasis/oasis.go#L418-L422

### LINKED ISSUE #2356: oasis-test-runner: Support specifying custom/extra log watcher handlers for each node
This should enable verifying that only certain nodes' logs contain a logging event or text.

### PR DESCRIPTION
**Pull request by tjanez**
This PR:

- Implements log watcher handler factories which makes it easy for each node to get its own set log watcher handlers.
- Enables specifying different log watcher handler factories for each node.

TODO:
- [x] Fix [End-to-End tests that fail](https://buildkite.com/oasislabs/oasis-core-ci/builds/672) due to this change.
- [x] Implement #2356 to enable fixing some failing End-to-End tests.

Closes #2355.
Closes #2356.

### CODE REVIEW

File: go/oasis-test-runner/log/log.go [hunk 1]
```diff
@@ -6,6 +6,12 @@ import (
 	"github.com/pkg/errors"
 )
 
+// WatcherHandlerFactory is a factory interface for log file watcher handlers.
+type WatcherHandlerFactory interface {
+	// Generate will generate and return a WatcherHandler ready for use.
+	Generate() (WatcherHandler, error)
```
Comment (kostko) [inline go/oasis-test-runner/log/log.go]: Maybe call it `NewHandler`, `New` or `Create` instead of `Generate`?

File: go/oasis-test-runner/log/handlers.go [hunk 2]
```diff
@@ -14,53 +23,94 @@ func (a *assertBase) fail() error {
...
-		assertBase: assertBase{message},
-		text:       text,
-		expected:   true,
+type assertContainsFactory struct {
+	assertContains
+}
+
+func (fac *assertContainsFactory) Generate() (WatcherHandler, error) {
+	return &assertContainsHandler{
+		assertContains: assertContains{
```
Comment (kostko) [inline go/oasis-test-runner/log/handlers.go]: Just passing `fac.assertContains` should be enough to create a copy (as composition is done by value not by pointer so value assignment should copy), so something like:
```suggestion
		assertContains: fac.assertContains,
```
Also elsewhere to simplify code.

File: go/oasis-test-runner/oasis/fixture.go [hunk 3]
```diff
@@ -118,6 +119,8 @@ type ValidatorFixture struct {
 
 	Entity int `json:"entity"`
 
+	LogWatcherHandlerFactories []log.WatcherHandlerFactory `json:"log_fac"`
```
Comment (kostko) [inline go/oasis-test-runner/oasis/fixture.go]: Fixtures are supposed to be serializable but factories currently are not. Either set `json:"-"` or make the factories serializable (probably something like having a registry of factory names and using the name on serialization and recreating from the registry on deserialization).

Also in other fixture structs.

File: go/oasis-test-runner/oasis/oasis.go [hunk 4]
```diff
@@ -55,6 +57,8 @@ type Node struct {
 
 	restartable bool
 	doStartNode func() error
+
+	LogWatcherHandlerFactories []log.WatcherHandlerFactory
```
Comment (kostko) [inline go/oasis-test-runner/oasis/oasis.go]: Group public fields together? Also do these need to be publicly mutable (probably not?) or can they be private and just have public accessor methods?

File: go/oasis-test-runner/scenario/e2e/basic.go [hunk 5]
```diff
@@ -121,21 +121,51 @@ func (sc *basicImpl) Fixture() (*oasis.NetworkFixture, error) {
 			},
 		},
 		Validators: []oasis.ValidatorFixture{
-			oasis.ValidatorFixture{Entity: 1},
-			oasis.ValidatorFixture{Entity: 1},
-			oasis.ValidatorFixture{Entity: 1},
+			oasis.ValidatorFixture{
+				Entity:                     1,
+				LogWatcherHandlerFactories: DefaultBasicLogWatcherHandlerFactories,
```
Comment (kostko) [inline go/oasis-test-runner/scenario/e2e/basic.go]: So network-wide defaults (e.g., for all nodes) are no longer supported? This seems annoying in case all the factories are the same.

File: go/oasis-test-runner/log/handlers.go (hunk 2 above)
Comment (tjanez) [reply go/oasis-test-runner/log/handlers.go]: Thanks for the tip!

Done.

File: go/oasis-test-runner/oasis/fixture.go (hunk 3 above)
Comment (tjanez) [reply go/oasis-test-runner/oasis/fixture.go]: I've set `json:"-"`.

File: go/oasis-test-runner/oasis/oasis.go (hunk 4 above)
Comment (tjanez) [reply go/oasis-test-runner/oasis/oasis.go]: Yes, they don't need to be publicly mutable. I've renamed them to `logWatcherHandlerFactories`.

File: go/oasis-test-runner/scenario/e2e/basic.go (hunk 5 above)
Comment (tjanez) [reply go/oasis-test-runner/scenario/e2e/basic.go]: Good suggestion. I've reworked the last commit to retain network-wide default log watcher handler factories and added the ability to enable/disable them in each node fixture (with sensible defaults).

File: go/oasis-test-runner/oasis/fixture.go [hunk 6]
```diff
@@ -296,6 +316,9 @@ type ByzantineFixture struct {
 	Script       string `json:"script"`
 	IdentitySeed string `json:"identity_seed"`
 	Entity       int    `json:"entity"`
+
+	EnableDefaultLogWatcherHandlerFactories bool                        `json:"enable_default_log_fac"`
```
Comment (kostko) [inline go/oasis-test-runner/oasis/fixture.go]: Why does the byzantine node fixture have this while others do not?

File: go/oasis-test-runner/oasis/fixture.go [hunk 7]
```diff
@@ -306,6 +329,10 @@ func (f *ByzantineFixture) Create(net *Network) (*Byzantine, error) {
 	}
 
 	return net.NewByzantine(&ByzantineCfg{
+		NodeCfg: NodeCfg{
+			DisableDefaultLogWatcherHandlerFactories: !f.EnableDefaultLogWatcherHandlerFactories,
```
Comment (kostko) [inline go/oasis-test-runner/oasis/fixture.go]: Is the reason for inverting it so that the default is "disabled"? Could we make it consistent in both structures?

Comment (tjanez) [reply go/oasis-test-runner/oasis/fixture.go]: My reasoning was to enable sensible defaults for different node types.

For example, Byzantine nodes should not have network's default log watcher handler factories enabled because they are byzantine and don't (always) report (their) byzantine behavior in their logs.
[Here](https://buildkite.com/oasislabs/oasis-core-ci/builds/847#f37f7791-1cfe-438c-b897-9479a58dd77c) is an example where honest nodes reported merge discrepancy but `byzantine-0` node didn't.

File: go/oasis-test-runner/oasis/fixture.go (hunk 6 above)
Comment (tjanez) [reply go/oasis-test-runner/oasis/fixture.go]: Other fixtures could have `DisableDefaultLogWatcherHandlerFactories bool` but I didn't include it everywhere to prevent "spam" the code too much since none of the current tests need that functionality.

It is trivial to add such a field when a node type would need it.

Comment (kostko) [reply go/oasis-test-runner/oasis/fixture.go]: Ok.

File: go/oasis-test-runner/oasis/fixture.go (hunk 7 above)
Comment (kostko) [reply go/oasis-test-runner/oasis/fixture.go]: Ok.
