### PR TITLE
go/runtime/committee: Close delay and reduced resets

### LINKED ISSUE #2825: Panic / crash when validator fails to query sentry for address
##### SUMMARY
In testing, I had a validator configured with 2 sentries; the validator was running but the sentries were not.  The validator was crashing (k8s pod restarting) and logs indicate a panic (appears unintentional).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
worker/registration

##### OASIS NODE VERSION

```paste below
Software version: 20.4.1
Runtime protocol version: 0.11.0
Consensus protocol version: 0.23.0
Committee protocol version: 0.8.0
Tendermint core version: 0.32.8
ABCI library version: 0.16.1
Go toolchain version: 1.13.9
```

##### OS / ENVIRONMENT

Binary was generated in golang:1.13-alpine (no rust binaries); running in alpine:latest.  Dockerfile available upon request.

##### ACTUAL RESULTS

Validator starts, but crashes soon after.

```paste below
level=warn module=grpc caller=clientconn.go:1283 ts=2020-04-06T16:21:15.239590709Z msg="grpc: addrConn.createTransport failed to connect to {100.71.164.162:9009 0  <nil>}. Err :connection error: desc = \"transport
level=info module=grpc caller=pickfirst.go:78 ts=2020-04-06T16:21:15.239632595Z msg="pickfirstBalancer: HandleSubConnStateChange: 0xc03a651780, TRANSIENT_FAILURE"
level=warn module=worker/registration caller=worker.go:585 ts=2020-04-06T16:21:15.239712554Z msg="failed to obtain addressesfrom sentry node" err="rpc error: code = Unavailable desc = all SubConns are in Transient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11e793e]
goroutine 141 [running]:
github.com/oasislabs/oasis-core/go/worker/registration.(*Worker).querySentries(0xc00d9886e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    github.com/oasislabs/oasis-core/go@/worker/registration/worker.go:591 +0x7fe
github.com/oasislabs/oasis-core/go/worker/registration.(*Worker).registerNode(0xc00d9886e0, 0x0, 0xc03aab2800, 0x2, 0xc00e406800)
    github.com/oasislabs/oasis-core/go@/worker/registration/worker.go:504 +0xba7
github.com/oasislabs/oasis-core/go/worker/registration.(*Worker).registrationLoop.func1.1(0xc03aab2820, 0xc03aab2820)
    github.com/oasislabs/oasis-core/go@/worker/registration/worker.go:194 +0x137
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc00d64fbe8, 0x1ac7a80, 0xc03aab2820, 0x0, 0x1ad1100, 0xc03a8aa370, 0x0, 0x0)
    github.com/cenkalti/backoff/v4@v4.0.0/retry.go:52 +0xf6
github.com/cenkalti/backoff/v4.RetryNotify(...)
    github.com/cenkalti/backoff/v4@v4.0.0/retry.go:31
github.com/cenkalti/backoff/v4.Retry(...)
    github.com/cenkalti/backoff/v4@v4.0.0/retry.go:25
github.com/oasislabs/oasis-core/go/worker/registration.(*Worker).registrationLoop.func1(0x0, 0xc03aab2800, 0x1, 0x1, 0x1)
    github.com/oasislabs/oasis-core/go@/worker/registration/worker.go:181 +0x1a6
github.com/oasislabs/oasis-core/go/worker/registration.(*Worker).registrationLoop(0xc00d9886e0)
    github.com/oasislabs/oasis-core/go@/worker/registration/worker.go:252 +0x2b4
github.com/oasislabs/oasis-core/go/worker/registration.(*Worker).doNodeRegistration(0xc00d9886e0)
    github.com/oasislabs/oasis-core/go@/worker/registration/worker.go:279 +0x64e
created by github.com/oasislabs/oasis-core/go/worker/registration.(*Worker).Start
    github.com/oasislabs/oasis-core/go@/worker/registration/worker.go:808 +0x163
```

##### EXPECTED RESULTS

I would expect the validator to either gracefully recover, or intentionally panic.

### PR DESCRIPTION
**Pull request by kostko**
Fixes #2825 

* go/runtime/committee: Introduce close delay when rotating connections

  Previously a connection was immediately closed, interrupting any in-flight
  requests. This introduces a configurable (via WithCloseDelay option) close
  delay so rotated connections are only closed after some time.
* go/runtime/committee: Don't reset committees when they don't change

  Previously each committee election triggered a reset of all connections for
  that committee. This changes the logic to just bump the committee version in
  case all the committee members are the same.

### CODE REVIEW

File: go/runtime/committee/committee.go [hunk 1]
```diff
@@ -86,14 +97,35 @@ Members:
...
 
-		_, err := cw.nw.WatchNode(ctx, member.PublicKey)
-		if err != nil {
+		filtered = append(filtered, member)
+	}
+
+	// If the set of (filtered) committee members did not change, there is no need to trigger a
+	// reset and recreate everything. Nodes will be updated anyway.
+	var cid hash.Hash
+	cid.From(filtered)
```
Comment (ptrus) [inline go/runtime/committee/committee.go:106]: should `filtered` be sorted so that order won't affect the hash? since looking at election code i think it's possible that the order changed but actual nodes are the same: https://github.com/oasislabs/oasis-core/blob/9e521ce7c57ca0e3cab7178eb43f5bca55b532e1/go/consensus/tendermint/apps/scheduler/scheduler.go#L477-L497

Comment (kostko) [reply go/runtime/committee/committee.go:106]: Yeah it should be, thanks!

Comment (kostko) [reply go/runtime/committee/committee.go:112]: Done.

Comment (ptrus) [reply go/runtime/committee/committee.go:112]: :heavy_check_mark:

File: go/runtime/committee/client.go [hunk 2]
```diff
@@ -132,6 +135,24 @@ type clientConnState struct {
...
+// DelayedClose closes the connection after the given delay. This method does not block the caller.
+func (cs *clientConnState) DelayedClose(delay time.Duration) {
+	go func() {
+		time.Sleep(delay)
+		cs.Close()
+	}()
+}
+
+// Close closes the connection.
+func (cs *clientConnState) Close() {
```
Comment (Yawning) [inline go/runtime/committee/client.go:147]: Should this nil out the relevant members?

Comment (kostko) [reply go/runtime/committee/client.go:147]: Yeah, fixed.
