### PR TITLE
oasis-test-runner: Use explicit flagsets for scenario parameters

### LINKED ISSUE #2897: Cannot set default values for E2E Scenarios Parameters
`Parameters()` methods always create new flagset instances, for example:
https://github.com/oasislabs/oasis-core/blob/35b7f62efec57e7fe638ad0aeee8e32962dbfc47/go/oasis-test-runner/scenario/e2e/e2e.go#L56-L61

That is problematic in conjunction with:
https://github.com/oasislabs/oasis-core/blob/35b7f62efec57e7fe638ad0aeee8e32962dbfc47/go/oasis-test-runner/cmd/root.go#L130-L138

IF a flag doesn't set existing parameter state as the default value, e.g.:
`fs.StringVar(&sc.nodeBinary, cfgNodeBinary, "<some-default>", "path to the node binary")`

The parameter will get overridden with the default value every time `Parameters()` is called. 

---

Suggested fix:
`Parameters()` methods creating new flagset instances is wrong, instead the flagset should be stored in the scenario struct and `Parameters()` should just return the stored flagset. However, `Clone()` should create a new instance of the flagset.

### PR DESCRIPTION
**Pull request by matevz**
Fixes #2897

### CODE REVIEW

File: go/oasis-test-runner/scenario/e2e/runtime.go [hunk 1]
```diff
@@ -69,60 +67,49 @@ type runtimeImpl struct {
...
+		e2eImpl:      *newE2eImpl(fullName),
+		clientBinary: clientBinary,
+		clientArgs:   clientArgs,
+	}
+
+	sc.flags.String(cfgClientBinaryDir, "", "path to the client binaries directory")
+	sc.flags.String(cfgRuntimeBinaryDir, "", "path to the runtime binaries directory")
+	sc.flags.String(cfgRuntimeLoader, "oasis-core-runtime-loader", "path to the runtime loader")
+	sc.flags.String(cfgTEEHardware, "", "TEE hardware to use")
+	sc.flags.Bool(cfgIasMock, true, "if mock IAS service should be used")
```
Comment (ptrus) [inline go/oasis-test-runner/scenario/e2e/runtime.go:89]: :+1:

File: go/oasis-test-runner/scenario/e2e/gas_fees_staking.go [hunk 2]
```diff
@@ -65,7 +65,11 @@ func (sc *gasFeesImpl) Fixture() (*oasis.NetworkFixture, error) {
 	}
 
 	var tee node.TEEHardware
-	err = tee.FromString(sc.TEEHardware)
+	teeStr, err := sc.flags.GetString(cfgTEEHardware)
+	if err != nil {
```
Comment (kostko) [inline go/oasis-test-runner/scenario/e2e/gas_fees_staking.go:69]: Huh, now we need to handle errors in all places where fetching flags? Does that mean that if you pass an invalid type (e.g., a string where an integer value is expected), the error will only be emitted once it hits the `Get*` call? Can you check?

It would be nice if this could be simplified.

**Comment by matevz** [comment]
Cloning scenario and its flagset is not as simple as I thought. Doing
```
newSc.flags =  flag.NewFlagSet(sc.name, flag.ContinueOnError)
newSc.flags.AddFlagSet(sc.flags)
```
keeps old references to values so the flagset is not correctly cloned. I will need to make separate helpers per scenario for copying the flags...

**Comment by matevz** [comment]
> Cloning scenario and its flagset is not as simple as I thought. Doing
> 
> ```
> newSc.flags =  flag.NewFlagSet(sc.name, flag.ContinueOnError)
> newSc.flags.AddFlagSet(sc.flags)
> ```
> 
> keeps old references to values so the flagset is not correctly cloned. I will need to make separate helpers per scenario for copying the flags...

This was now solved in d676397195e2bd68faf62a5f88aca7d7dda40a3c

File: go/oasis-test-runner/scenario/e2e/gas_fees_staking.go (hunk 2 above)
Comment (matevz) [reply go/oasis-test-runner/scenario/e2e/gas_fees_staking.go:69]: Actually all setter functions for flags are called when setting up scenarios (when generating individual parameter sets), so if you pass invalid value (e.g. string instead of int), it will correctly complain.

Comment (matevz) [reply go/oasis-test-runner/scenario/e2e/gas_fees_staking.go:69]: > It would be nice if this could be simplified.

The idea was that flags are now explicit to separate them from other non-settable scenario fields. Before they were just wrappers around scenario variables and initialization/usage was unclear.

Comment (matevz) [reply go/oasis-test-runner/scenario/e2e/gas_fees_staking.go]: I added `getTEEHardware()` helper which does this now.

Comment (kostko) [reply go/oasis-test-runner/scenario/e2e/gas_fees_staking.go]: > Actually all setter functions for flags are called when setting up scenarios (when generating individual parameter sets), so if you pass invalid value (e.g. string instead of int), it will correctly complain.

So when can this actually return an error?

Comment (matevz) [reply go/oasis-test-runner/scenario/e2e/gas_fees_staking.go]: > So when can this (e.g., the `Get*` methods) actually return an error?

If a programmer registers a flag as fs.String(cfgMyFlag) and then he calls GetInt(cfgMyFlag). The new `getTEEHardware()` helper returns error, if TEE flag is invalid (it's not either `""` or `"intel-sgx"`).

Comment (kostko) [reply go/oasis-test-runner/scenario/e2e/gas_fees_staking.go]: This should be a panic (programmer error) not a runtime error.

File: go/oasis-test-runner/scenario/e2e/e2e.go [hunk 3]
```diff
@@ -27,37 +28,50 @@ type e2eImpl struct {
...
-		nodeBinary: "oasis-node",
+	// Empty scenario name is used for registering global parameters only.
+	fullName := "e2e"
+	if name != "" {
+		fullName += "/" + name
+	}
+
+	sc := &e2eImpl{
+		name:   fullName,
+		logger: logging.GetLogger("scenario/e2e/" + name),
```
Comment (ptrus) [inline go/oasis-test-runner/scenario/e2e/e2e.go:43]: if `name == ""` then this will be `"scenario/e2e/"`? maybe use `"scenario/fullName"`

File: go/oasis-test-runner/scenario/e2e/gas_fees_staking.go (hunk 2 above)
Comment (matevz) [reply go/oasis-test-runner/scenario/e2e/gas_fees_staking.go]: We'll just ignore those for now as `viper` does.

File: go/oasis-test-runner/scenario/e2e/e2e.go [hunk 4]
```diff
@@ -12,52 +12,64 @@ import (
...
-		name:       sc.name,
-		logger:     sc.logger,
-		nodeBinary: sc.nodeBinary,
+	newSc := &e2eImpl{
+		net:    sc.net,
+		name:   sc.name,
+		logger: sc.logger,
+		flags:  newE2eFlags(sc.name),
 	}
+	scenario.CopyFlagValues(newSc.flags, sc.flags)
```
Comment (kostko) [inline go/oasis-test-runner/scenario/e2e/e2e.go:62]: This seems slightly awkward, can you instead define your own flagset like this:
```golang
type FlagSet struct {
    flag.FlagSet
}
```
And then define a `Clone()` method on it that returns a cloned flagset? Put it under the `env` package.

Actually I see that you already do this for `env.ParameterFlagSet`, why not use that type everywhere (e.g., make `Parameters()` return a `*ParameterFlagSet`) and add a `Clone()` method?

Comment (matevz) [reply go/oasis-test-runner/scenario/e2e/e2e.go]: I pushed a draft version of the Clone() method. This seems to work, but it's ugly - I need to use `reflect` package to copy the interface.

Comment (matevz) [reply go/oasis-test-runner/scenario/e2e/e2e.go]: cleaned up, ready for review

File: go/oasis-test-runner/env/env.go [hunk 5]
```diff
@@ -52,6 +53,27 @@ func (pfs *ParameterFlagSet) MarshalJSON() ([]byte, error) {
 	return json.Marshal(ps)
 }
 
+// Clone clones the parameter flagset.
+//
+// This function is usually called when cloning scenarios where we also want to clone existing
+// parameter values.
+func (pfs *ParameterFlagSet) Clone() *ParameterFlagSet {
+	// XXX: pfs.name and pfs.errorHandling are private. Use reflection.
```
Comment (kostko) [inline go/oasis-test-runner/env/env.go:61]: Is this just to get the two parameters from the constructor? Why not add a `NewParameterFlagSet` function and record these two arguments in `ParameterFlagSet` instead?

File: go/oasis-test-runner/env/env.go [hunk 6]
```diff
@@ -25,6 +26,8 @@ type CleanupFn func()
 // ParameterFlagSet is a wrapper for flag.FlagSet to produce nicer JSON output.
 type ParameterFlagSet struct {
 	flag.FlagSet
+	name          string
```
Comment (kostko) [inline go/oasis-test-runner/env/env.go:29]: Blank line above.

File: go/oasis-test-runner/scenario/e2e/runtime.go [hunk 7]
```diff
@@ -250,13 +232,23 @@ func (sc *runtimeImpl) start(childEnv *env.Env) (<-chan error, *exec.Cmd, error)
 	return clientErrCh, cmd, nil
 }
 
+// getTEEHardware returns TEEHardware based on viper parameter.
```
Comment (kostko) [inline go/oasis-test-runner/scenario/e2e/runtime.go:235]:
```suggestion
// getTEEHardware returns the configured TEE hardware.
```
